# Generated by Django 5.2.7 on 2025-10-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096)),
                ('author_code', models.CharField(max_length=3)),
                ('date', models.DateField(auto_now=True)),
                ('subject', models.CharField(max_length=64)),
                ('subject_code', models.CharField(max_length=3)),
            ],
        ),
    ]
