# Generated by Django 5.2.7 on 2025-10-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='PLR', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('size_is_A4', models.CharField(choices=[(True, 'A4'), (False, 'A5')], max_length=2)),
                ('diary_is_weekly', models.BooleanField(choices=[(True, 'Week per View'), (False, 'Day per Page')])),
                ('cover_type', models.BooleanField(choices=[(True, 'Normal'), (False, 'Bespoke')])),
            ],
        ),
    ]
