# Generated by Django 5.2.7 on 2025-10-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=128)),
                ('school_code', models.CharField(max_length=10)),
                ('contact_first_name', models.CharField(max_length=64)),
                ('contact_last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_is_A4',
            field=models.BooleanField(choices=[(True, 'A4'), (False, 'A5')]),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_stamp', models.DateTimeField(auto_now=True)),
                ('item_list', models.JSONField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('complete', models.BooleanField(default=False)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.schools')),
            ],
        ),
    ]
