# Generated by Django 5.2.7 on 2025-10-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_schools_alter_blog_text_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item_list',
        ),
        migrations.AddField(
            model_name='orders',
            name='invoice',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
